# Generated by Django 5.0.6 on 2024-07-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('idcourse', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('hour', models.IntegerField(verbose_name='Horas')),
                ('credits', models.IntegerField(verbose_name='Créditos')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
